### PR TITLE
IS22 Verify Add Password Fields Are Valid

### LINKED ISSUE #22: Verify that add password fields are valid

### LINKED ISSUE #29: Check DGV is not empty before indexing
DeleteButton_Click method in MainView.cs

Logging in as a new user with no password and clicking random buttons breaks things. Edit password -> okay causes crashing.

### PR DESCRIPTION
**Pull request by willem445**
closes #22 
closes #29

### CODE REVIEW

File: PasswordVault/Views/MainView.cs [hunk 1]
```diff
@@ -404,6 +436,31 @@ public void DisplayAddPasswordResult(AddPasswordResult result)
...
 		*================================================================================================*/
+        /*************************************************************************************************/
+        private void UpdateStatus(string message, ErrorLevel errorLevel)
+        {
+            userStatusLabel.Text = message;
+
+            switch (errorLevel)
+            {
+                case ErrorLevel.Error:
+                    userStatusLabel.ForeColor = Color.FromArgb(0xFF0000);
```
Comment (willem445) [inline PasswordVault/Views/MainView.cs]: Colors should be consts

File: PasswordVault/Views/MainView.cs [hunk 2]
```diff
@@ -490,15 +547,18 @@ private void RaiseAddPasswordEvent(string application, string username, string d
         /*************************************************************************************************/
         private void EditButton_Click(object sender, EventArgs e)
         {
-            editCancelButton.Enabled = true;
-            editCancelButton.Visible = true;
-            _editMode = true;
-            addButton.Text = "Ok";
+            if (passwordDataGridView.Rows.Count > 1)
```
Comment (willem445) [inline PasswordVault/Views/MainView.cs]: Magic number
